datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus-operated:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 300ms
  - name: Loki
    type: loki
    access: proxy
    orgId: 2
    url: http://loki:3100
    isDefault: false
    editable: false
  - name: Postgres
    type: postgres
    access: proxy
    orgId: 3
    url: postgres-postgresql:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: password
    jsonData:
      tlsAuth: false
      tlsSkipVerify: true
      sslmode: disable
    isDefault: false
    editable: false
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    orgId: 4
    url: elasticsearch-elasticsearch-master:9200

