datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus-operated:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 300ms
  - name: Loki
    type: loki
    access: proxy
    orgId: 3
    url: http://loki:3100
    isDefault: false
    editable: false