name: Infrastructure
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - 'terragrunt/**/*'
      - '.github/workflows/infrastructure.yaml'
jobs:
  deploy_infra:
    name: Deploy Infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Image
        working-directory: ./terragrunt
        run: |
          make build
      - name: Authenticate Google SDK
        working-directory: ./terragrunt
        env:
          GCP_TERRAFORM_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.GCP_TERRAFORM_SERVICE_ACCOUNT_KEY_FILE }}
        run: |
          echo $GCP_TERRAFORM_SERVICE_ACCOUNT_KEY_FILE > key-file.json
          make authci
      - name: Provision Resources
        working-directory: ./terragrunt
        env:
          TERRAGRUNT_AUTO_INIT: "true"
        run: |
          make terraform
      - name: Get Terraform Output
        working-directory: ./terragrunt
        run: |
          make terraform-output
      - name: Install GCloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: foodify-281512
          service_account_key: ${{ secrets.GCP_TERRAFORM_SERVICE_ACCOUNT_KEY_FILE }}
      - name: Configure Kubectl
        run: |
          gcloud container clusters get-credentials $(jq -rs '.[2].gke_cluster_name.value' terragrunt/output.json) --region $(jq -rs '.[2].gke_cluster_location.value' terragrunt/output.json) --project foodify-281512
      - name: Install CRDs
        run: |
          kubectl apply -f tools/crd/prometheus.yaml

