name: Infrastructure
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - 'terragrunt/**/*'
jobs:
  deploy_infra:
    name: Deploy Infra
    runs-on: ubuntu-latest
    steps:
      - name: Build Image
        run: |
          make build
