name: Infrastructure
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - 'terragrunt/**/*'
      - '.github/workflows/infrastructure.yaml'
jobs:
  deploy_infra:
    name: Deploy Infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Build Image
        working-directory: ./terragrunt
        run: |
          make build
      - name: Authenticate Google SDK
        working-directory: ./terragrunt
        env:
          GCP_TERRAFORM_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.GCP_TERRAFORM_SERVICE_ACCOUNT_KEY_FILE }}
        run: |
          echo $GCP_TERRAFORM_SERVICE_ACCOUNT_KEY_FILE > key-file.json
          make authci
      - name: Provision Resources
        working-directory: ./terragrunt
        run: |
          make terraform
