name: Remove old artifacts

on:
  schedule:
    # Every day at 1am
    - cron: '0/5 * * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 sec'
          skip-recent: 5
